# Site settings
title: MonsterSlayer's Way 
email: dongyado@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
    A place to write some words.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dongyado.github.io" # the base hostname & protocol for your site
twitter_username: dongyado
github_username:  dongyado

# Build settings
markdown: kramdown
