# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: pygments
markdown: redcarpet
redcarpet:
      extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

sass:
    style: :compressed
    sass_dir: _sass

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: MonsterSlayer

description: 生命不止，折腾不息
author:
  name: MonsterSlayer
  email: dongyado@gmail.com 
  github: dongyado
  twitter: dongyado
  linkedin: dongyado
  bio: 生命不止，折腾不息 
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

BASE_PATH:
