# Site settings
title: 八小时工作，八小时生活，八小时窝着
author: MonsterSlayer
author_avatar: /images/header.jpg
email: alias@domain.tld
description: 八小时工作，八小时生活，八小时窝着
url: "https://dongyado.github.io"
domain: "http://dongyado.com"
github_username: dongyado
github_site_repo: dongyado/dongyado.github.io
disqus: monsterslayer


# Build settings
highlighter: rouge
markdown: kramdown
kramdown:
    syntax_highlighter: rouge
    extensions: ["fenced_code_blocks", "autolink", "tables", "smart"]

sass:
    style: :compressed
    sass_dir: _sass

permalink: pretty
excerpt_separator: "<!-- more -->"

# path
categories_path: categories/
tags_path: tags/


gems:
  - jekyll-sitemap
